// Map provider names to your exact image paths
const providerImageMap = {
  "Fresh Bloom Florists": "/florist.jpg",
  "Elite Tutors Academy": "/tutors.jpg",
  "Spark Plumbing Solutions": "/plumber.jpg",
  "Swift Movers": "/movers.png",
  "Logistics Experts": "/logistics.png",
  "Fitness Pro Trainers": "/fitness.jpg",
  "Relax & Spa": "/spa.jpg",
  "Little Stars Daycare": "/Daycare.jpg",
  "Electric Repairs Co.": "/electric repairs.jpg",
  "Tutors Plus": "/tutorss.jpg",
  "Luxury Pet Care": "/pet care.jpg",
  "Super Car Wash": "/car wash.jpg",
  "Event Management Hub": "/event manage.jpg",
  "Green Thumb Gardening": "/gardening.jpg",
  "Master Painter Services": "/painter.jpg",
  "Nutritionist Clinic": "/nutritionist.jpg",
  "Tailor & Stitch": "/tailor.jpg",
  "Foodie Delights": "/food.jpg",
  "Pro Photographer": "/photographer.jpg",
  "Mental Health Experts": "/mental health.jpg",
  "Network Repair Pros": "/network repair.jpg",
  "Computer Repair Co.": "/computer repairs.jpg",
  "Home Cleaning Services": "/home cleaner.jpg",
  "NutriLife": "/nutri.jpg",
  "Royal Event Planner": "/royal event planner.jpg",
  "Hair Dresser Salon": "/hair dresser.jpg"
};
